# Generated by Django 6.0.5 on 2026-05-26 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empleado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("Mesero", "Mesero"),
                    ("Cajero", "Cajero"),
                    ("Administrador", "Administrador"),
                ],
                max_length=50,
            ),
        ),
    ]
