# Generated by Django 6.0.5 on 2026-05-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_empleado_user_alter_empleado_cargo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Permiso",
            },
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="cargo",
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "permisos",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="gestion.permiso"
                    ),
                ),
            ],
            options={
                "db_table": "Rol",
            },
        ),
        migrations.AddField(
            model_name="empleado",
            name="rol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.rol",
            ),
        ),
    ]
